---
- hosts: webservers
  become: yes
  become_method: sudo
  pre_tasks:
    - name: Add repo for php7.0
      apt_repository:
        repo: "ppa:ondrej/php"
        update_cache: yes
  roles:
   - git
   - httpd
   - php
   - handlers
   - clone
   
      
