---
- name: restart apache2
  service:
    name: apache2
    state: restarted

- name: reload httpd
  service:
    name: apache2
    state: reloaded

- name: start httpd
  service:
    name: apache2
    state: started

- name: stop httpd
  service:
    name: apache2
    state: stopped
