---
- name: Ensure /var/www/html directory has correct permissions.
  file:
    path: /var/www/html
    state: directory
    owner: ec2-user
    group: ec2-user

- name: Ensure .ssh directory exists.
  file:
    path: /var/www/.ssh
    state: directory
    mode: 0700
    owner: ec2-user
    group: ec2-user

- name: Ensure GitHub deploy key is present on the server.
  copy:
    content: 'deploy key hier'
    dest: /var/www/.ssh/deploy_key
    mode: 0600
    owner: ec2-user
    group: ec2-user

- name: Ensure setfacl support is present.
  package: name=acl

- name: Clone the code repository to the docroot.
  git:
    repo: https://github.com/Fewty/CloudAndAutomation.git
    dest: /var/www/html
    accept_hostkey: yes
    key_file: /var/www/.ssh/deploy_key
  become_user: ec2-user