---
- name: Ensure /var/www/html directory has correct permissions.
  file:
    path: /var/www/html
    state: directory
    owner: root
    group: root

- name: Ensure .ssh directory exists.
  file:
    path: /var/www/.ssh
    state: directory
    mode: 0700
    owner: root
    group: root

- name: Ensure GitHub deploy key is present on the server.
  copy:
    content: 'Webserver'
    dest: /var/www/.ssh/deploy_key
    mode: 0600
    owner: root
    group: root

- name: Ensure setfacl support is present.
  package: name=acl

- name: Clone the code repository to the docroot.
  git:
    repo: https://github.com/Fewty/CloudAndAutomation.git
    dest: /var/www/html
    accept_hostkey: yes
    key_file: /var/www/.ssh/deploy_key
  become_user: root

- name: start apache services
  service:
    name: apache2
    state: started
