---
- name: Install Apache2 on the target machines
  apt:
     name: apache2
     state: present
     update_cache: yes
  notify:
  - restart apache

- name: ensure httpd is running
  service:
    name: apache2
    state: started
